name:                Get
version:             0.2018.1.10
github:              "MarisaKirisame/Get"
license:             BSD3
author:              "Marisa Kirisame"
maintainer:          "lolisa@marisa.moe"
copyright:           "2018 Marisa Kirisame"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            get stuff out of stuff
category:            control

description:         Please see the README on Github at <https://github.com/MarisaKirisame/Get#readme>

dependencies:
- base >= 4.7 && < 5
- singletons >= 2.3.1
- constraints >= 0.9.1

library:
  source-dirs: src

tests:
  Get-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Get
